"""
coding_executor.py
==================
CodingExecutor — project scaffolding and code generation.

This is the first multi-executor orchestrator in JARVIS.
It delegates to FileExecutor for file I/O and TerminalExecutor
for syntax checking / test running.

Supported actions
-----------------
generate_project_structure : create folder tree for a project
write_starter_files        : generate language-appropriate starter files
generate_flask_project     : full Flask API scaffold
generate_python_script     : single Python script with boilerplate
verify_syntax              : run py_compile on a file
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import List

from jarvis.execution.execution_context import ExecutionContext, RiskLevel
from jarvis.execution.sandbox import sandbox
from jarvis.skills.base import BaseExecutor

logger = logging.getLogger(__name__)


# ── Code templates ─────────────────────────────────────────────────────────────

def _flask_app_py(project_name: str) -> str:
    return f'''\
"""
{project_name} — Flask API
Generated by JARVIS.
"""

from flask import Flask, jsonify, request

app = Flask(__name__)


@app.route("/", methods=["GET"])
def index():
    return jsonify({{"message": "Welcome to {project_name} API", "status": "ok"}})


@app.route("/health", methods=["GET"])
def health():
    return jsonify({{"status": "healthy"}})


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
'''


def _flask_requirements() -> str:
    return "flask>=3.0.0\nrequests>=2.31.0\n"


def _generic_main_py(project_name: str, goal: str) -> str:
    return f'''\
"""
{project_name}
Goal: {goal}
Generated by JARVIS.
"""

import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def main():
    logger.info("Starting {project_name}")
    # TODO: implement main logic
    pass


if __name__ == "__main__":
    main()
'''


def _gitignore() -> str:
    return (
        "__pycache__/\n*.pyc\n*.pyo\n.env\n.venv\nvenv/\n"
        "*.egg-info/\ndist/\nbuild/\n.pytest_cache/\n"
    )


def _readme(project_name: str, goal: str, requirements: List[str]) -> str:
    reqs_md = "\n".join(f"- {r}" for r in requirements) or "- (none specified)"
    return (
        f"# {project_name}\n\n"
        f"> {goal}\n\n"
        f"## Requirements\n\n{reqs_md}\n\n"
        f"## Setup\n\n"
        f"```bash\npip install -r requirements.txt\npython main.py\n```\n\n"
        f"## Generated by\n\nJARVIS AI Operating System\n"
    )


# ── Executor ───────────────────────────────────────────────────────────────────

class CodingExecutor(BaseExecutor):

    SUPPORTED_ACTIONS = [
        "generate_project_structure",
        "write_starter_files",
        "generate_flask_project",
        "generate_python_script",
        "verify_syntax",
    ]

    ACTION_RISK_MAP = {
        "generate_project_structure": RiskLevel.LOW,
        "write_starter_files":        RiskLevel.LOW,
        "generate_flask_project":     RiskLevel.LOW,
        "generate_python_script":     RiskLevel.LOW,
        "verify_syntax":              RiskLevel.MEDIUM,
    }

    # ── Action handlers ────────────────────────────────────────────────────────

    def _action_generate_project_structure(self, ctx: ExecutionContext) -> str:
        project_name = ctx.params.get("project_name", "project")
        goal         = ctx.params.get("goal", "")
        requirements = ctx.params.get("requirements", [])

        project_dir = sandbox.ensure_dir(project_name)
        sandbox.ensure_dir(f"{project_name}/tests")
        sandbox.ensure_dir(f"{project_name}/docs")

        # Detect project type from goal text
        goal_lower = goal.lower()
        if any(kw in goal_lower for kw in ["flask", "api", "rest", "web"]):
            self._scaffold_flask(project_name, goal, requirements)
        else:
            self._scaffold_generic(project_name, goal, requirements)

        logger.info(f"CodingExecutor: scaffolded {project_name}")
        return f"Project structure created: {sandbox.relative_display(project_dir)}"

    def _action_write_starter_files(self, ctx: ExecutionContext) -> str:
        project_name = ctx.params.get("project_name", "project")
        goal         = ctx.params.get("goal", "")
        requirements = ctx.params.get("requirements", [])

        # Write .gitignore
        gi_path = sandbox.resolve(f"{project_name}/.gitignore")
        if not gi_path.exists():
            gi_path.write_text(_gitignore(), encoding="utf-8")

        # Write requirements.txt
        req_path = sandbox.resolve(f"{project_name}/requirements.txt")
        if not req_path.exists():
            goal_lower = goal.lower()
            if any(kw in goal_lower for kw in ["flask", "api", "rest", "web"]):
                req_path.write_text(_flask_requirements(), encoding="utf-8")
            else:
                req_path.write_text("# Add your dependencies here\n", encoding="utf-8")

        logger.info(f"CodingExecutor: starter files written for {project_name}")
        return f"Starter files written in: {project_name}/"

    def _action_generate_flask_project(self, ctx: ExecutionContext) -> str:
        project_name = ctx.params.get("project_name", "flask_api")
        goal         = ctx.params.get("goal", "Flask API")
        requirements = ctx.params.get("requirements", [])
        self._scaffold_flask(project_name, goal, requirements)
        return f"Flask project generated: {project_name}/"

    def _action_generate_python_script(self, ctx: ExecutionContext) -> str:
        script_name  = ctx.params.get("script_name", "script.py")
        project_name = ctx.params.get("project_name", ".")
        goal         = ctx.params.get("goal", "")

        path = sandbox.resolve(f"{project_name}/{script_name}")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            _generic_main_py(script_name.replace(".py", ""), goal),
            encoding="utf-8",
        )
        logger.info(f"CodingExecutor: generated script {path}")
        return f"Script generated: {sandbox.relative_display(path)}"

    def _action_verify_syntax(self, ctx: ExecutionContext) -> str:
        script_path = ctx.params.get("script_path", "")
        safe_path   = sandbox.resolve(script_path)

        if not safe_path.exists():
            raise FileNotFoundError(f"Script not found: {script_path}")

        import subprocess
        result = subprocess.run(
            ["python", "-m", "py_compile", str(safe_path)],
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode != 0:
            raise SyntaxError(
                f"Syntax error in {script_path}:\n{result.stderr.strip()}"
            )
        return f"Syntax OK: {sandbox.relative_display(safe_path)}"

    # ── Scaffold helpers ───────────────────────────────────────────────────────

    def _scaffold_flask(
        self, project_name: str, goal: str, requirements: List[str]
    ) -> None:
        files = {
            f"{project_name}/app.py":            _flask_app_py(project_name),
            f"{project_name}/requirements.txt":  _flask_requirements(),
            f"{project_name}/README.md":         _readme(project_name, goal, requirements),
            f"{project_name}/.gitignore":        _gitignore(),
            f"{project_name}/tests/__init__.py": "",
            f"{project_name}/tests/test_app.py": (
                f'"""Tests for {project_name}"""\n\n'
                f"import pytest\n\n\n"
                f"def test_placeholder():\n    assert True\n"
            ),
        }
        self._write_files(files)

    def _scaffold_generic(
        self, project_name: str, goal: str, requirements: List[str]
    ) -> None:
        files = {
            f"{project_name}/main.py":           _generic_main_py(project_name, goal),
            f"{project_name}/requirements.txt":  "# Add your dependencies here\n",
            f"{project_name}/README.md":         _readme(project_name, goal, requirements),
            f"{project_name}/.gitignore":        _gitignore(),
            f"{project_name}/tests/__init__.py": "",
        }
        self._write_files(files)

    @staticmethod
    def _write_files(files: dict) -> None:
        for rel_path, content in files.items():
            target = sandbox.resolve(rel_path)
            if not target.exists():
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
                logger.debug(f"CodingExecutor: wrote {target}")
